### PR TITLE
 ems v3.36, mc4plus v3.29, mc2plus v3.20, 2foc v3.3.4

### PR DESCRIPTION
**Pull request by Nicogene**
- ems (v3.36, release date 2021.02.01 @ 17:24),
 - mc4plus  (release date 2021.02.01 @ 17:24)
 - mc2plus (v3.20, release date 2021.02.01 @ 17:24)
 - 2foc (v3.3.4, release date 2021.02.01 @ 17:24)

### CODE REVIEW

**Comment by traversaro** [comment]
Can you add a reference on the sha of icub-firmware and icub-firmware-shared as done for other commit in the past, see https://github.com/robotology/icub-firmware-build/commit/ebbfa2a536e966f21010b1db3cb10fd830ab1562 .

**Review by marcoaccame — CHANGES_REQUESTED** [review]
Hi @Nicogene,

it is important to add some more information to the commit log, so that we can always:
- discriminate this binary from another one by querying its version
- understand what new features / fixes this particular build has
- to be able to recompile the same binary from sources.

For this reason we typically have logs in this format:

```
2foc v3.3.3

- built on 28 aug 2019 using icub-firmware devel w/ SHA-1: 04621ce09a8c267bfab2b499e8b69dd8e8b3da71
- main changes from previous release v3.3.1 are:
  - PWM frequency increased from 20 kHz to 40 kHz
- fixes with respect to release v3.3.2 are:
  - data in CAN messages is readed byte-aligned
``` 

and 

```
ems v3.34, mc4plus v3.27, mc2plus v3.18

 - ems v3.34 release date 2020 dec 9 @ 14:28
 - mc4plus v3.27 release date 2020 dec 9 @ 14:31
 - mc2plus v3.18 release date 2020 dec 9 @ 14:32

- built on 2020 dec 9 using icub-firmware devel w/ SHA-1: 6f3fe1895151cc30d6d5300be156183dd31c5658 and icub-firmware-shared devel w/ SHA-1: 7cf3ccf5c470be8302395c9e50502f8fa55e61c8
- main changes from previous release are:
  - increased mn protocol version from 2.16 to 2.17 (added configuration for pos service)
  - increased as protocol version from 1.4 to 1.5 (added the new entity pos)

```

Not every log is always coherent to this standard, but we should aim at perfection :smile:

Can you please integrate the log information of the new binaries with info about the used sha and the new features?

**Comment by traversaro** [comment]
cc @GiulioRomualdi @isorrentino

**Review by marcoaccame — APPROVED** [review]
ok.

**Pull request merged**
