### PR TITLE
Update ems v3.87, mc4plus v3.90, mc2plus 3.69, amc 2.2 and bat v1.3.4

### PR DESCRIPTION
**Pull request by MSECode**
Changes in this PR:

- Update status bat to uint16_t for struct eOas_battery_timedvalue_t valid for both BAT and BMS devices
- Add total absorbed current to BAT yarp port
- Set BAT port voltage as the INPUT voltage
- Move the calculation of the BAT Battery_Charge from the methods related to the display only to a proper place with an ad-hoc function
- Add to diagnostic parser overheating error
- Re-elaborate status bat-bms using uint16_t as datatype and using string_view instead of string for status messages
Update bat reading values adding total absorbed current in BAT and adjusting limits for BAT SoC calculation
- Fix datatype in diagnostic to be aligned by raw value datatype Set value of battery charge to NaN if equal to zero
- Update MINIMUM_REQUIRED_icub_firmware_shared_VERSION to 1.38.2
- Update bat v1.3.4, ems v3.87, mc4plus v3.90, mc2plus 3.69, amc 2.2

Related to: 
- https://github.com/robotology/icub-main/pull/953
- https://github.com/robotology/icub-firmware/pull/487
- https://github.com/robotology/icub-firmware-shared/pull/95

### CODE REVIEW

**Review by valegagge — APPROVED** [review]
LGTM

**Review by marcoaccame — CHANGES_REQUESTED** [review]
Hi @MSECode, the following PR needs some changes that require recompilation of the binaries:
- https://github.com/robotology/icub-firmware-shared/pull/95

**Comment by MSECode** [comment]
> Hi @MSECode, the following PR needs some changes that require recompilation of the binaries:
> 
> * [Update CMakeLists.txt with icub_firmware_shared version to 1.38.2 icub-firmware-shared#95](https://github.com/robotology/icub-firmware-shared/pull/95)

Which changes are you referring to actually, since I don't see any particular change request in https://github.com/robotology/icub-firmware-shared/pull/95

**Comment by MSECode** [comment]
> Hi @MSECode, the following PR needs some changes that require recompilation of the binaries:
> 
> * [Update CMakeLists.txt with icub_firmware_shared version to 1.38.2 icub-firmware-shared#95](https://github.com/robotology/icub-firmware-shared/pull/95)

Hi @marcoaccame,
Updated protocol version to 1.11 in  `eth/embobj/plus/comm-v2/protocol/api/EoProtocolAS.h` and pushed udpated binaries

**Pull request merged**
