### PR TITLE
Update boards firmware amc v101.2, amc v102.2, ems v3.66, mc4plus v3.69, mc2plus v3.48

### PR DESCRIPTION
**Pull request by MSECode**

### CODE REVIEW

**Comment by MSECode** [comment]
Open PR for binary files of `mc4plus` `mc2plus` `amc` `ems` 
cc: @valegagge @sgiraz @AntonioConsilvio

**Comment by marcoaccame** [comment]
@MSECode: you have probably missed some commits in the PR of the source code https://github.com/robotology/icub-firmware/pull/363 because in there I don't see the new version for the boards yet:

**Comment by MSECode** [comment]
Yes, that's correct
I'll update the versioning with a commit toward the source code of icub-firmware 
So I'll update this PR

**Review by marcoaccame — APPROVED** [review]
ok by me

**Pull request merged**
