### PR TITLE
2foc pwm feedback bugfix

### PR DESCRIPTION
**Pull request by ale-git**
2foc pwm bugfix in:

- 2foc.hex
- 2foc.r1.dc.hex
- 2foc.r1.uarm.hex
- 2foc.r1.worm.hex

built from icub-firmware devel 262fae7209d13e6142d27cf3c2373c38b63cd18c

See https://github.com/robotology/icub-firmware/pull/177.

### CODE REVIEW

**Comment by pattacini** [comment]
@ale-git 
Actually, the commit should be https://github.com/robotology/icub-firmware/commit/04788d2fe807668450f6e3510e1f857f6fe59c8c.

**Review by marcoaccame — CHANGES_REQUESTED** [review]
Hi @ale-git, pls remember updating https://github.com/robotology/icub-firmware-build/blob/devel/info/firmware.info.xml w/ the new application versions:
- https://github.com/robotology/icub-firmware-build/blob/devel/info/firmware.info.xml#L78
- etc. for the other versions used on R1

**Comment by ale-git** [comment]
Hi @marcoaccame I've updated the info/firmware.info.xml file with the new versions.

**Comment by ale-git** [comment]
@pattacini I've generated the binaries from the latest devel branch in robotology

**Comment by marcoaccame** [comment]
Hi @ale-git ... I have spotted only now that there are two binaries of the 2foc w/ the same version number, namely `2foc.hex` and `2foc.r1.uarm.hex`. 

The effect is that by looking at the version detected by `FirmwareUpdater` we cannot understand if on R1 there is the standard `2foc.he`x or the `2foc.r1.uarm.hex`.

We should think a bit of how to solve it.

**Comment by ale-git** [comment]
Hi @marcoaccame, I changed his major version to 6. Mybe keeping different major versions will do the job?

**Comment by marcoaccame** [comment]
> Hi @marcoaccame, I changed his major version to 6. Mybe keeping different major versions will do the job?

Hi @ale-git: yes, that seems ok. Thank you.

**Review by marcoaccame — APPROVED** [review]
ok now.

**Pull request merged**
