### PR TITLE
mc4plus v3.65: calibration type6 with FAP 

### PR DESCRIPTION
**Pull request by MSECode**
Adding executable for mc4plus board 
with code for performing calibration type 6 with FAP for arm fingers

### CODE REVIEW

**Comment by MSECode** [comment]
@valegagge can you please check this PR so I can then make the PR from my forked devel to origin devel.
Thanks.

PS: let me know if you can check the files of my fork, otherwise I'll grant u access

**Comment by MSECode** [comment]
So,
checked/tested  the executable on arm bench setup and calibration and open-close movement work fine.
The PR can be merged
cc: @valegagge @marcoaccame

**Comment by marcoaccame** [comment]
Hi @MSECode, I will have a look at the PR later today.

**Review by marcoaccame — CHANGES_REQUESTED** [review]
Hi, just one thing:
- update also the following [file](https://github.com/robotology/icub-firmware-build/blob/devel/info/firmware.info.xml#L56) w/ the new application version of the mc4plus.

And for next time mention the version of the binary in the PR / commit as in [here](https://github.com/robotology/icub-firmware-build/pull/72), so that it appears in the log.

**Comment by MSECode** [comment]
Update info xml file with updated version 3.65 for `mc4plus`

**Review by marcoaccame — APPROVED** [review]

**Pull request merged**
