### PR TITLE
EMS + 2foc firmware for iCub3 able to recover fom AMO errors

### PR DESCRIPTION
**Pull request by ale-git**
Added EMS + 2foc firmware for iCub3 .hex files.

This firmware version is able to recover fom AMO errors, using the motor encoder when the difference between the motor encoder and the AMO sensor exceeds 1 degree.

They must be used only in iCub V3 (back compatible versions coming soon).

The EMS version is 3.43, the 2foc version is 3.3.12

### CODE REVIEW

**Comment by ale-git** [comment]
https://github.com/icub-tech-iit/fix/issues/892

**Comment by ale-git** [comment]
Hi @S-Dafarra

**Comment by ale-git** [comment]
As requested by DIC we shall place the binaries in a single repo/branch.

Here are the main decisions:
- We shall place all the special binaries in `robotology/icub-firmware-build/devel`  close to the official ones, but with a different name `xxx.icub3.hex`, different application version and a clear log of what they do.
- For now we shall put the new binaries as they are, so that we can quickly have them stored and DIC can test them at their earliest convenience.
- We shall then rebase the source code of the experimental binaries vs latest `robotology/devel`, so that we can always have any newly added other feature. 
- In the medium term we shall merge the experimental features into `roebotology/devel` so that we can have again a single binary which can detect if it runs in icub3 and behave properly. For instance, in a very simple ways: if AMO are requested we surely have icub3.
- When we have tested that a single binary works for legacy robots and icub3 we shall delete the `xxx.icub3.hex` files.

The new binaries are: `ems.icub3.hex` and `2foc.icb3.hex`

**Review by marcoaccame — APPROVED** [review]
👍

**Comment by pattacini** [comment]
Hi @ale-git @marcoaccame @traversaro 

I've just added up the following intermediate point:
>In the short term, we shall publish the source code that has generated the binaries as a branch or fork and clarify the link between the two.

In this regard, @ale-git, could you point @giovannipizzolante and @GiulioRomualdi to the source code you used to generate these binaries?

**Comment by pattacini** [comment]
It turned out that the source code is hosted at https://github.com/ale-git/icub-firmware/tree/tame-AMOs/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3.

@ale-git, just keep a note of the slight modification done to the policy above.

**Pull request merged**
